services:
  faster-whisper-api:
    build: .
    image: faster-whisper-api
    container_name: faster-whisper-api
    volumes:
      - "./data:/data"
      - "./data/cache/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]