services:
  faster-whisper-api:
    image: ghcr.io/kinqdos/faster-whisper-api
    container_name: faster-whisper-api
    volumes:
      - "./data:/app/data"
      - "./cache/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]