[project]
name = "faster-whisper-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "faster-whisper>=1.1.1",
    "pydantic>=2.11.7",
    "python-multipart>=0.0.20",
]
